# permissions for end users to edit parents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-controller
    app.kubernetes.io/managed-by: kustomize
  name: cluster-editor-role
rules:
- apiGroups:
  - cluster.lambda.coffee
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.lambda.coffee
  resources:
  - clusters/status
  verbs:
  - get
